#!/bin/sh
#
# `source activate` initial conditional check to determine which `source activate` to actually run
#
# assumes that activate.* can be found on the $PATH
#

# error clause
echo `ps -p $$ | sed 's|.*csh|THIS-IS-CSH|' | grep CSH || eval echo '$0'`                           \
     "`ps -p $$ | tr '\n' ' '`"                                                                     \
     "`test -x /usr/bin/lsb_release && lsb_release -si | sed 's| ||' || uname -s`"                  \
     "$SHLVL"                                                                                       \
     "activate"                                                                                     \
     "error-clause" | awk -f "`which whichshell.awk`"                                               &&\
bash -c "echo '[ACTIVATE]: ERROR: Only supports sourcing from tcsh/csh and bash/zsh/dash/posh.' 1>&2"

# bourne shell clause (bash/zsh/dash/posh)
echo `ps -p $$ | sed 's|.*csh|THIS-IS-CSH|' | grep CSH || eval echo '$0'`                           \
     "`ps -p $$ | tr '\n' ' '`"                                                                     \
     "`test -x /usr/bin/lsb_release && lsb_release -si | sed 's| ||' || uname -s`"                  \
     "$SHLVL"                                                                                       \
     "activate"                                                                                     \
     "bourne-shell-clause" | awk -f "`which whichshell.awk`"                                        &&\
. "`which activate.sh`" && return

# c-shell clause (tcsh/csh)
echo `ps -p $$ | sed 's|.*csh|THIS-IS-CSH|' | grep CSH || eval echo '$0'`                           \
     "`ps -p $$ | tr '\n' ' '`"                                                                     \
     "`test -x /usr/bin/lsb_release && lsb_release -si | sed 's| ||' || uname -s`"                  \
     "$SHLVL"                                                                                       \
     "activate"                                                                                     \
     "c-shell-clause" | awk -f "`which whichshell.awk`"                                             &&\
source "`which activate.csh`" && exit $status
