#!/usr/bin/env bash
###########################################################################
# the above shebang is irrelevant since this is supposed to be sourced    #
# it just forces bad executions of this to be in a supported shell that   #
# can error properly                                                      #
###########################################################################

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #                                                                     # #
# # DEACTIVATE                                                          # #
# # if tree that determined which deactivate script to run              # #
# #                                                                     # #
# # the setuptools will properly substitute the CONDA_INSTALL_PREFIX    # #
# # upon install into the conda executable bin (see the install_scripts # #
# # function of setup.py)                                               # #
# #                                                                     # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

###########################################################################
# ERROR CLAUSE                                                            #
${CONDA_INSTALL_PREFIX}/whichshell_args.bash                              \
    "deactivate"                                                          \
    "error-clause"                                                        \
    `${CONDA_INSTALL_PREFIX}/whichshell_ps.bash && eval 'echo $0' || echo 'csh'` | \
awk -f "${CONDA_INSTALL_PREFIX}/whichshell.awk" &&                        \
    : ||                                                                  \
    :
# END ERROR CLAUSE                                                        #
###########################################################################

###########################################################################
# BOURNE SHELL CLAUSE                                                     #
# bash/zsh/dash/posh/ksh                                                  #
${CONDA_INSTALL_PREFIX}/whichshell_args.bash                              \
    "deactivate"                                                          \
    "bourne-shell-clause"                                                 \
    `${CONDA_INSTALL_PREFIX}/whichshell_ps.bash && eval 'echo $0' || echo 'csh'` | \
awk -f "${CONDA_INSTALL_PREFIX}/whichshell.awk" &&                        \
    . ${CONDA_INSTALL_PREFIX}/deactivate.sh ||                            \
    :
# END BOURNE SHELL CLAUSE                                                 #
###########################################################################

###########################################################################
# C-SHELL CLAUSE                                                          #
# tcsh/csh                                                                #
${CONDA_INSTALL_PREFIX}/whichshell_args.bash                              \
    "deactivate"                                                          \
    "c-shell-clause"                                                      \
    `${CONDA_INSTALL_PREFIX}/whichshell_ps.bash && eval 'echo $0' || echo 'csh'` | \
awk -f "${CONDA_INSTALL_PREFIX}/whichshell.awk" &&                        \
    source "${CONDA_INSTALL_PREFIX}/deactivate.csh" ||                    \
    :
# END C-SHELL CLAUSE                                                      #
###########################################################################

###########################################################################
# NO-OP RETURN                                                            #
# this will ensure that deactivate will consistently return               #
#                                                                         #
# since we rely heavily on the usage of return codes to detect what       #
# scripts to run above, zero vs non-zero return codes does not            #
# necessarily mean error                                                  #
:
# END NO-OP RETURN                                                        #
###########################################################################
