#!/usr/bin/env bash
###########################################################################
# the above shebang is irrelevant since this is supposed to be sourced    #
# it just forces bad executions of this to be in a supported shell that   #
# can error properly                                                      #
###########################################################################

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #                                                                     # #
# # TEST_WHICHSHELL                                                     # #
# # interact with the whichshell* scripts to see how they respond in    # #
# # certain scenarios                                                   # #
# #                                                                     # #
# # the setuptools will properly substitute the CONDA_INSTALL_PREFIX    # #
# # upon install into the conda executable bin (see the install_scripts # #
# # function of setup.py)                                               # #
# #                                                                     # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

echo "TEST_WHICHSHELL"
echo ""

echo "WHICHSHELL_PS.BASH"
${CONDA_INSTALL_PREFIX}/whichshell_ps.bash && echo "NOT (t)csh" || echo "IS (t)csh"
${CONDA_INSTALL_PREFIX}/whichshell_ps.bash && eval 'echo $0' || echo "csh"
echo ""

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

echo "WHICHSHELL_ARGS.BASH: ERROR-CLAUSE"
${CONDA_INSTALL_PREFIX}/whichshell_args.bash                              \
    "test_whichshell"                                                     \
    "error-clause"                                                        \
    `${CONDA_INSTALL_PREFIX}/whichshell_ps.bash && eval 'echo $0' || echo "csh"`
echo ""

echo "WHICHSHELL_ARGS.BASH: BOURNE-SHELL-CLAUSE"
${CONDA_INSTALL_PREFIX}/whichshell_args.bash                              \
    "test_whichshell"                                                     \
    "bourne-shell-clause"                                                 \
    `${CONDA_INSTALL_PREFIX}/whichshell_ps.bash && eval 'echo $0' || echo "csh"`
echo ""

echo "WHICHSHELL_ARGS.BASH: C-SHELL-CLAUSE"
${CONDA_INSTALL_PREFIX}/whichshell_args.bash                              \
    "test_whichshell"                                                     \
    "c-shell-clause"                                                      \
    `${CONDA_INSTALL_PREFIX}/whichshell_ps.bash && eval 'echo $0' || echo "csh"`
echo ""

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

echo "WHICHSHELL.AWK: ERROR-CLAUSE"
${CONDA_INSTALL_PREFIX}/whichshell_args.bash                              \
    "test_whichshell"                                                     \
    "error-clause"                                                        \
    `${CONDA_INSTALL_PREFIX}/whichshell_ps.bash && eval 'echo $0' || echo "csh"` | \
awk -f "${CONDA_INSTALL_PREFIX}/whichshell.awk" &&                        \
    echo "++ SELECTED ++" ||                                              \
    :
echo ""

echo "WHICHSHELL.AWK: BOURNE-SHELL-CLAUSE"
${CONDA_INSTALL_PREFIX}/whichshell_args.bash                              \
    "test_whichshell"                                                     \
    "bourne-shell-clause"                                                 \
    `${CONDA_INSTALL_PREFIX}/whichshell_ps.bash && eval 'echo $0' || echo "csh"` | \
awk -f "${CONDA_INSTALL_PREFIX}/whichshell.awk" &&                        \
    echo "++ SELECTED ++" ||                                              \
    :
echo ""

echo "WHICHSHELL.AWK: C-SHELL-CLAUSE"
${CONDA_INSTALL_PREFIX}/whichshell_args.bash                              \
    "test_whichshell"                                                     \
    "c-shell-clause"                                                      \
    `${CONDA_INSTALL_PREFIX}/whichshell_ps.bash && eval 'echo $0' || echo "csh"` | \
awk -f "${CONDA_INSTALL_PREFIX}/whichshell.awk" &&                        \
    echo "++ SELECTED ++" ||                                              \
    :
echo ""
