package:
  name: conda
  # VERSION_OVERRIDE is used by the canary release workflow
  version: {{ os.getenv("VERSION_OVERRIDE") or GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}

source:
  # git_url only captures committed code
  git_url: ../
  folder: conda-src

build:
  script: {{ PYTHON }} -m pip install conda-src/ --no-deps --no-build-isolation -vv && {{ PYTHON }} -m conda init --install
  # These are present when the new environment is created
  # so we have to exempt them from the list of initial files
  # for conda-build to realize they should be included.
  always_include_files:
    - bin/conda                    # [unix]
    - bin/activate                 # [unix]
    - bin/deactivate               # [unix]
    - Scripts/activate.bat         # [win]
    - Scripts/activate             # [win]
    - Scripts/deactivate           # [win]

requirements:
  build:
    - git  # for source/git_url above
  host:
    - python
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
    # for `conda init` in build/script above
    - boltons >=23.0.0
    - frozendict >=2.4.2
    - menuinst >=2
    - platformdirs >=3.10.0
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - tqdm >=4
  run:
    - archspec >=0.2.3
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=25.4.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - frozendict >=2.4.2
    - jsonpatch >=1.32
    - menuinst >=2
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0           # [py>=310]
    - zstandard >=0.15
  run_constrained:
    - conda-build >=25.9
    - conda-content-trust >=0.1.1
    - conda-env >=2.6

test:
  imports:
    # high-level imports
    - conda
    - conda_env
    # new/updated submodules (can be dropped after 1-2 releases)
    - conda.gateways.repodata.jlap
    - conda.plugins.subcommands.doctor
  commands:
    # builtin subcommands
    - conda --help
    - conda clean --help
    - conda compare --help
    - conda config --help
    - conda create --help
    - conda info --help
    - conda init --help
    - conda install --help
    - conda list --help
    - conda notices --help
    - conda package --help
    - conda remove --help
    - conda rename --help
    - conda run --help
    - conda search --help
    - conda update --help
    - conda upgrade --help
    # plugin subcommands
    - conda doctor --help

about:
  home: https://conda.org
  license: BSD-3-Clause
  license_file: conda-src/LICENSE
  summary: Canary release of conda
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/conda/conda
