coverage:
  precision: 2
  round: nearest
  range: 60...100
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true

ignore:
  - conda/_vendor.py
  - conda/cli/main_package.py
  - conda/exports.py
  - conda/gateways/connection/adapters/ftp.py
  - conda/gateways/connection/adapters/s3.py
  - tests/.*

comment: off
