version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      # Unshallow the git clone to make sure we can identify the version
      - git fetch --unshallow
    pre_install:
      - git update-index --assume-unchanged docs/requirements.txt docs/source/conf.py
      - python -m pip install --editable --no-deps --no-cache-dir .
    pre_build:
      - python docs/source/_ext/conda_umls.py
  apt_packages:
    # Needed for the UML graph Sphinx extension
    - graphviz
    - default-jre

python:
  install:
    - requirements: docs/requirements.txt
