@startuml
!include <C4/C4_Dynamic>
!include Base.puml

System(conda, "conda", "Software package and environment management system")
SystemDb_Ext(channels, "Channels", "Software package storage systems")

' Include relationships here once we've set the differences.
!include Rels.puml

@enduml
