# edit this in https://github.com/conda/infrastructure

name: Bug Report
description: Create a bug report.
labels:
  - type::bug
body:
  - type: markdown
    attributes:
      value: |
        Because processing new bug reports is time-consuming, we would like to ask you to fill out the following form to the best of your ability and as completely as possible.

        > [!NOTE]
        > Bug reports that are incomplete or missing information may be closed as inactionable.

        Since there are already a lot of open issues, please also take a moment to search existing ones to see if your bug has already been reported. If you find something related, please upvote that issue and provide additional details as necessary.

        💐 Thank you for helping to make `conda/infrastructure` better. We would be unable to improve `conda/infrastructure` without our community!
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm and check all of the following options.
      options:
        - label: I added a descriptive title
          required: true
        - label: I searched open reports and couldn't find a duplicate
          required: true
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What should have happened instead? Please provide as many details as possible. The more information provided, the more likely we are able to replicate your problem and offer a solution.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Include any additional information (or screenshots) that you think would be valuable.
