flowchart LR
    logger_0["conda"]
    logger_1["conda.activate"]
    logger_2["conda.auxlib.entity"]
    logger_3["conda.auxlib.exceptions"]
    logger_4["conda.auxlib.ish"]
    logger_5["conda.auxlib.logz"]
    logger_6["conda.base.context"]
    logger_7["conda.cli.conda_argparse"]
    logger_8["conda.cli.install"]
    logger_9["conda.cli.main_clean"]
    logger_10["conda.cli.main_compare"]
    logger_11["conda.cli.main_create"]
    logger_12["conda.cli.main_info"]
    logger_13["conda.cli.main_init"]
    logger_14["conda.cli.main_list"]
    logger_15["conda.cli.main_pip"]
    logger_16["conda.cli.main_remove"]
    logger_17["conda.cli.main_run"]
    logger_18["conda.cli.python_api"]
    logger_19["conda.common.configuration"]
    logger_20["conda.common.io"]
    logger_21["conda.common._logic"]
    logger_22["conda.common._os"]
    logger_23["conda.common._os.linux"]
    logger_24["conda.common._os.unix"]
    logger_25["conda.common._os.windows"]
    logger_26["conda.common.path"]
    logger_27["conda.common.pkg_formats.python"]
    logger_28["conda.common.serialize"]
    logger_29["conda.common.signals"]
    logger_30["conda.common.toposort"]
    logger_31["conda.core.envs_manager"]
    logger_32["conda.core.index"]
    logger_33["conda.core.initialize"]
    logger_34["conda.core.link"]
    logger_35["conda.core.package_cache_data"]
    logger_36["conda.core.path_actions"]
    logger_37["conda.core.portability"]
    logger_38["conda.core.prefix_data"]
    logger_39["conda.core.solve"]
    logger_40["conda.core.subdir_data"]
    logger_41["conda.env.installers.pip"]
    logger_42["conda.env.pip_util"]
    logger_43["conda.exception_handler"]
    logger_44["conda.exceptions"]
    logger_45["conda.gateways.anaconda_client"]
    logger_46["conda.gateways.connection.adapters.ftp"]
    logger_47["conda.gateways.connection.adapters.localfs"]
    logger_48["conda.gateways.connection.adapters.s3"]
    logger_49["conda.gateways.connection.download"]
    logger_50["conda.gateways.connection.session"]
    logger_51["conda.gateways.disk"]
    logger_52["conda.gateways.disk.create"]
    logger_53["conda.gateways.disk.delete"]
    logger_54["conda.gateways.disk.link"]
    logger_55["conda.gateways.disk.permissions"]
    logger_56["conda.gateways.disk.read"]
    logger_57["conda.gateways.disk.test"]
    logger_58["conda.gateways.disk.update"]
    logger_59["conda.gateways.logging"]
    logger_60["conda.gateways.repodata"]
    logger_61["conda.gateways.repodata.jlap.core"]
    logger_62["conda.gateways.repodata.jlap.fetch"]
    logger_63["conda.gateways.repodata.jlap.interface"]
    logger_64["conda.gateways.subprocess"]
    logger_65["conda.history"]
    logger_66["conda.instructions"]
    logger_67["conda.models.channel"]
    logger_68["conda.models.dist"]
    logger_69["conda.models.leased_path_entry"]
    logger_70["conda.models.match_spec"]
    logger_71["conda.models.package_info"]
    logger_72["conda.models.prefix_graph"]
    logger_73["conda.models.version"]
    logger_74["conda.notices.cache"]
    logger_75["conda.notices.core"]
    logger_76["conda.notices.fetch"]
    logger_77["conda.plan"]
    logger_78["conda.plugins.hookspec"]
    logger_79["conda.plugins.manager"]
    logger_80["conda.plugins.subcommands.doctor.health_checks"]
    logger_81["conda.resolve"]
    logger_82["conda.testing"]
    logger_83["conda.testing.integration"]
    logger_84["conda.trust.signature_verification"]
    logger_85["conda.utils"]
    logger_86["conda._vendor.distro"]
    logger_0 --> logger_1
    logger_0 --> logger_2
    logger_0 --> logger_3
    logger_0 --> logger_4
    logger_0 --> logger_5
    logger_0 --> logger_6
    logger_0 --> logger_7
    logger_0 --> logger_8
    logger_0 --> logger_9
    logger_0 --> logger_10
    logger_0 --> logger_11
    logger_0 --> logger_12
    logger_0 --> logger_13
    logger_0 --> logger_14
    logger_0 --> logger_15
    logger_0 --> logger_16
    logger_0 --> logger_17
    logger_0 --> logger_18
    logger_0 --> logger_19
    logger_0 --> logger_20
    logger_0 --> logger_21
    logger_0 --> logger_22
    logger_22 --> logger_23
    logger_22 --> logger_24
    logger_22 --> logger_25
    logger_0 --> logger_26
    logger_0 --> logger_27
    logger_0 --> logger_28
    logger_0 --> logger_29
    logger_0 --> logger_30
    logger_0 --> logger_31
    logger_0 --> logger_32
    logger_0 --> logger_33
    logger_0 --> logger_34
    logger_0 --> logger_35
    logger_0 --> logger_36
    logger_0 --> logger_37
    logger_0 --> logger_38
    logger_0 --> logger_39
    logger_0 --> logger_40
    logger_0 --> logger_41
    logger_0 --> logger_42
    logger_0 --> logger_43
    logger_0 --> logger_44
    logger_0 --> logger_45
    logger_0 --> logger_46
    logger_0 --> logger_47
    logger_0 --> logger_48
    logger_0 --> logger_49
    logger_0 --> logger_50
    logger_0 --> logger_51
    logger_51 --> logger_52
    logger_51 --> logger_53
    logger_51 --> logger_54
    logger_51 --> logger_55
    logger_51 --> logger_56
    logger_51 --> logger_57
    logger_51 --> logger_58
    logger_0 --> logger_59
    logger_0 --> logger_60
    logger_60 --> logger_61
    logger_60 --> logger_62
    logger_60 --> logger_63
    logger_0 --> logger_64
    logger_0 --> logger_65
    logger_0 --> logger_66
    logger_0 --> logger_67
    logger_0 --> logger_68
    logger_0 --> logger_69
    logger_0 --> logger_70
    logger_0 --> logger_71
    logger_0 --> logger_72
    logger_0 --> logger_73
    logger_0 --> logger_74
    logger_0 --> logger_75
    logger_0 --> logger_76
    logger_0 --> logger_77
    logger_0 --> logger_78
    logger_0 --> logger_79
    logger_0 --> logger_80
    logger_0 --> logger_81
    logger_0 --> logger_82
    logger_82 --> logger_83
    logger_0 --> logger_84
    logger_0 --> logger_85
    logger_0 --> logger_86
