flowchart LR
    python --> bzip2
    python --> libffi
    python --> libzlib
    python --> ncurses
    python --> openssl
    python --> readline
    python --> sqlite
    python --> tk
    python --> tzdata
    python --> xz
    python --> libsqlite
    python --> libcxx
    python --> zlib
    python --> __osx
    python --> liblzma
    python --> libexpat
    python --> libmpdec
    python --> python_abi
    python --> zstd
    python --> _python_rc
    python --> expat
    python --> libiconv
    libsqlite --> icu
    openssl --> ca-certificates
    python_abi --> pypy3.6
    python_abi --> pypy3.7
    python_abi --> pypy3.8
    python_abi --> pypy3.9
    xz --> liblzma-devel
    xz --> xz-gpl-tools
    xz --> xz-tools
    zstd --> lz4-c
    ca-certificates --> __win
    ca-certificates --> __unix
