schema_version: 1

context:
  version: '312'

package:
  name: pywin32
  version: ${{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b${{ version }}.tar.gz
  sha256: 71d959a9f18cf86001e5dca1e30d5046c187eabbb08112cb6ff01e04689f6f7b
  patches:
    - patches/0001-conda-forge-fixes.patch

build:
  number: 0

requirements:
  build:
    - if: win and python_impl != 'pypy'
      then:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
        - ${{ compiler("cxx") }}
  host:
    - python
    - if: win and python_impl != 'pypy'
      then:
        - pip
        - setuptools
  run:
    - python

tests:
  - requirements:
      run:
        - python
    script: run_test.py

about:
  license: PSF-2.0
  license_file: pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  homepage: https://github.com/mhammond/pywin32
  repository: https://github.com/mhammond/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
    - xhochy
