#!/usr/bin/env python
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
import fileinput
import os
import sys

from pylint.pyreverse.main import Run

here = os.path.dirname(__file__)


# files and folders to ignore during generating the UML files
ignore = [
    "_vendor.py",
    "compat.py",
    "misc.py",
    "utils.py",
    "exports.py",
    "api.py",
]

# additional PLantUML directives to add
extra_puml = "\n".join(
    [
        "left to right direction",
        "skinparam nodesep 5",
        "skinparam ranksep 5",
    ]
)

# some replacement to patch the PlantUML generated by pyreverse
replacements = (
    (
        "set namespaceSeparator none",
        f"set namespaceSeparator none\n{extra_puml}",
    ),
    (
        'class "" as conda.common.compat.six_with_metaclass.',
        'class "six_with_metaclass" as conda.common.compat.six_with_metaclass.',
    ),
)


def post_process(files, output_path):
    """Replace all items from the replacements list above in the given files."""
    for file in files:
        with fileinput.input(
            files=[os.path.join(output_path, file)], inplace=True
        ) as open_file:
            for line in open_file:
                for old, new in replacements:
                    line = line.replace(old, new)
                sys.stdout.write(line)


def generate_pumls(app=None, config=None):
    """
    Generates PlantUML files for the given packages and writes
    the files to the components directory in the documentation source.
    """
    sys.stdout.write("Generating PlantUML...\n")
    sys.stdout.flush()
    # TODO: make this a configurable thing via the docs config
    packages = ["conda"]

    for package in packages:
        output_path = os.path.join(here, "..", "dev-guide", "umls")
        output_format = "puml"
        files = [
            f"packages_{package}.{output_format}",
            f"classes_{package}.{output_format}",
        ]
        ignore_list = ",".join(ignore)
        args = [
            package,
            f"--ignore={ignore_list}",
            f"--output={output_format}",
            "--colorized",
            "--max-color-depth=8",
            f"--project={package}",
            f"--output-directory={output_path}",
            "--all-associated",
            # Causes an EmptyNode AttributeError: https://github.com/pylint-dev/pylint/issues/10767
            # This allows more of the inheritance hierarchy to be shown, however the Level 4 C4
            # diagram is already too detailed.
            # "--all-ancestors",
        ]
        # Run pyreverse to create the files first
        exit_code = Run(args).run()
        if exit_code:
            raise SystemExit(exit_code)
        # Then post-process the generated files to fix some things.
        post_process(files, output_path)
        sys.stdout.write("Done generating PlantUML files.\n")


def setup(app):
    if "AUTOBUILD" not in os.environ:
        app.connect("config-inited", generate_pumls)

    return {
        "version": "0.1",
        "parallel_read_safe": False,
        "parallel_write_safe": False,
    }


if __name__ == "__main__":
    generate_pumls()
