#!/usr/bin/env python3
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
"""Generate a test-recipes README from rendered package metadata.

This reads rendered recipe metadata from package artifacts in
``tests/data/test-recipes``:
- ``*.tar.bz2`` packages: ``info/recipe/meta.yaml``
- ``*.conda`` packages: ``info-*.tar.zst`` component -> ``info/recipe/meta.yaml``
"""

from __future__ import annotations

import sys
import tarfile
import zipfile
from dataclasses import dataclass
from itertools import groupby
from pathlib import Path
from typing import TYPE_CHECKING

try:
    import yaml  # type: ignore[import-not-found]
except ModuleNotFoundError:
    raise ImportError(
        "PyYAML is required to parse recipe metadata. "
        "Run via pre-commit or install pyyaml."
    )

if sys.version_info < (3, 14):
    raise ImportError(
        "Python 3.14+ is required to parse .conda package metadata. "
        "Run via pre-commit or install Python 3.14+."
    )

if TYPE_CHECKING:
    from collections.abc import Iterator

RECIPES_ROOT = Path(__file__).parent
CHANNEL_ROOT = RECIPES_ROOT.parent / "test-recipes"
README = RECIPES_ROOT / "README.md"
UNKNOWN = "-"


@dataclass(frozen=True)
class RecipeInfo:
    artifact: str
    subdir: str
    package: str | None
    version: str | None
    purpose: str | None


def _normalize(value: object) -> str | None:
    if value is None:
        return None
    return " ".join(str(value).split())


def _extract_meta(tf: tarfile.TarFile) -> str | None:
    for member in tf:
        if member.name == "info/recipe/meta.yaml":
            stream = tf.extractfile(member)
            return stream.read().decode("utf-8") if stream else None
    return None


def _read_meta_from_tar_bz2(artifact: Path) -> str | None:
    # .tar.bz2 is a tarfile of files
    with tarfile.open(artifact, mode="r|bz2") as tf:
        return _extract_meta(tf)


def _read_meta_from_conda(artifact: Path) -> str | None:
    # .conda is a zipfile of tar.zst files
    with zipfile.ZipFile(artifact) as zf:
        try:
            name = next(
                name
                for name in zf.namelist()
                if name.startswith("info-") and name.endswith(".tar.zst")
            )
        except StopIteration:
            return None
        with zf.open(name) as stream, tarfile.open(fileobj=stream, mode="r|zst") as tf:
            return _extract_meta(tf)


def _read_rendered_meta(artifact: Path) -> str | None:
    if not artifact.is_file():
        return None
    elif artifact.name.endswith(".conda"):
        return _read_meta_from_conda(artifact)
    elif artifact.name.endswith(".tar.bz2"):
        return _read_meta_from_tar_bz2(artifact)
    return None


def _parse_artifact(artifact: Path) -> RecipeInfo | None:
    meta_yaml_text = _read_rendered_meta(artifact)
    if not meta_yaml_text:
        return None

    try:
        parsed = yaml.safe_load(meta_yaml_text) or {}
    except yaml.YAMLError as exc:
        raise ValueError("Failed to parse rendered recipe metadata") from exc

    package = parsed.get("package")
    extra = parsed.get("extra")
    if not isinstance(package, dict):
        package = {}
    if not isinstance(extra, dict):
        extra = {}

    return RecipeInfo(
        artifact=artifact.name,
        subdir=artifact.parent.name,
        package=_normalize(package.get("name")),
        version=_normalize(package.get("version")),
        purpose=_normalize(extra.get("test_purpose")),
    )


def _generate_readme(grouped: list[list[RecipeInfo]]) -> Iterator[str]:
    yield "# Test Recipes"
    yield ""
    yield "<!-- This file is generated by tests/data/recipes/generate_recipes_readme.py -->"
    yield "<!-- Run: python tests/data/recipes/generate_recipes_readme.py -->"
    yield ""
    yield "Overview of package artifacts and their intended purpose."
    yield ""
    yield "| Package | Version | Subdirs | Purpose |"
    yield "| --- | --- | --- | --- |"
    details = []
    for recipes in grouped:
        if not recipes:
            continue
        versions = "<br>".join(
            f"`{version}`"
            for version in sorted(
                {recipe.version for recipe in recipes if recipe.version}
            )
        )
        subdirs = "<br>".join(
            f"`{subdir}`" for subdir in sorted({recipe.subdir for recipe in recipes})
        )
        recipe = recipes[0]
        link = ""
        if purpose := list(
            {recipe.purpose: recipe for recipe in recipes if recipe.purpose}.values()
        ):
            details.append(purpose)
            link = f"[#{recipe.package}](#{recipe.package})"
        yield f"| `{recipe.package}` | {versions} | {subdirs} | {link} |"
    yield ""
    for recipes in details:
        yield f"## {recipes[0].package}"
        for recipe in recipes:
            if len(recipes) > 1:
                yield f"### `{recipe.version}` `{recipe.subdir}`"
            yield f"{recipe.purpose}"
        yield ""


def main() -> int:
    recipes = sorted(
        (
            info
            for subdir in next(CHANNEL_ROOT.walk())[1]
            for artifact in (CHANNEL_ROOT / subdir).iterdir()
            if (info := _parse_artifact(artifact))
        ),
        key=lambda recipe: recipe.artifact,
    )
    grouped = [
        list(recipes)
        for _, recipes in groupby(recipes, key=lambda recipe: recipe.package)
    ]
    rendered = "\n".join(_generate_readme(grouped))
    README.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
