package:
  name: conda
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  # git_url is nice in that it won't capture devenv stuff.  However, it only
  #    captures committed code, so pay attention.
  git_url: ../

build:
  # These are present when the new environment is created
  # so we have to exempt them from the list of initial files
  # for conda-build to realize they should be included.
  always_include_files:
    - bin/conda                    # [unix]
    - bin/activate                 # [unix]
    - bin/deactivate               # [unix]
    - Scripts/activate.bat         # [win]
    - Scripts/activate             # [win]
    - Scripts/deactivate           # [win]

requirements:
  build:
    - m2-filesystem                # [win]
    - m2-bash                      # [win]
    - m2-base                      # [win]

  host:
    - python
    - conda-package-handling >=1.3.0
    - menuinst >=1.4.11,<2         # [win]
    - pip
    - ruamel_yaml >=0.11.14,<0.17
    - setuptools >=31.0.1
  run:
    - python
    - conda-package-handling >=1.3.0
    - menuinst >=1.4.11,<2         # [win]
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - requests >=2.18.4,<3
    - ruamel_yaml >=0.11.14,<0.17
    - setuptools >=31.0.1
  run_constrained:
    - conda-build >=3
    - conda-env >=2.6
    - conda-content-trust >=0.1.1
    - cytoolz >=0.8.1

test:
  source_files:
    - tests
    - setup.cfg
  requires:
    - mock
    - pytest
    - pexpect
    - responses
    - conda-build
    - m2-filesystem  # [win]
    - m2-bash        # [win]
    - m2-base        # [win]
  imports:
    - conda
    - conda_env

about:
  home: https://conda.io
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package and environment manager.
  description: >
    Conda is an open source package management system and environment
    management system for installing multiple versions of software packages
    and their dependencies and switching easily between them. It works on
    Linux, OS X and Windows, and was created for Python programs but can
    package and distribute any software.
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/conda/conda

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - chenghlee
    - jezdez
    - kenodegard
