# edit this in https://github.com/conda/infrastructure

name: Prepare authors

on:
  # https://crontab.guru/#0_3_*_*_1
  schedule:
    - cron: '0 3 * * 1'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  prepare:
    if: '!github.event.repository.fork'
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Prepare Authors
        uses: conda/actions/prepare-authors@210fa69f0b174ee4ea463a3a5402ec5a1d95d6db # v26.9.0
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          since: tag
          base-branch: main
