# edit this in https://github.com/conda/infrastructure

name: Prepare release notes

on:
  workflow_run:
    workflows:
      - 'Tests'
    types:
      - completed
    branches:
      - '[0-9].*.x'
      - '[0-9][0-9].*.x'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  queue: max
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  prepare:
    if: >-
      github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.event == 'push'
      && github.event.workflow_run.head_repository.full_name == github.repository
    runs-on: ubuntu-slim
    steps:
      - name: Prepare Release Notes
        uses: conda/actions/prepare-release@d88418cd4e36358ba51e7c88f2d2d5edb9ac49e7 #v26.8.1
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          news-directory: news
          changelog-path: CHANGELOG.md
          release-branch-pattern: |
            [0-9].*.x
            [0-9][0-9].*.x
